sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=gsgayatri
    - REGISTRY_PASS="Gayatri@27"

before_install:
  - docker build -t gsgayatri/docker-react -f Dockerfile.dev .

script:
  - docker run gsgayatri/docker-react npm run test -- --coverage

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push gsgayatri/docker-react
  on:
    branch: master
#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"

